#!/bin/bash
wget -r ftp://prism.nacse.org/daily/tmin/1980/ 
wget -r ftp://prism.nacse.org/daily/tmin/1981/
wget -r ftp://prism.nacse.org/daily/tmin/1982/ 
wget -r ftp://prism.nacse.org/daily/tmin/1983/ 
wget -r ftp://prism.nacse.org/daily/tmin/1984/ 
wget -r ftp://prism.nacse.org/daily/tmin/1985/ 
wget -r ftp://prism.nacse.org/daily/tmin/1986/ 
wget -r ftp://prism.nacse.org/daily/tmin/1987/ 
wget -r ftp://prism.nacse.org/daily/tmin/1988/ 
wget -r ftp://prism.nacse.org/daily/tmin/1989/ 
wget -r ftp://prism.nacse.org/daily/tmin/1990/ 
wget -r ftp://prism.nacse.org/daily/tmin/1991/
wget -r ftp://prism.nacse.org/daily/tmin/1992/ 
wget -r ftp://prism.nacse.org/daily/tmin/1993/ 
wget -r ftp://prism.nacse.org/daily/tmin/1994/ 
wget -r ftp://prism.nacse.org/daily/tmin/1995/ 
wget -r ftp://prism.nacse.org/daily/tmin/1996/ 
wget -r ftp://prism.nacse.org/daily/tmin/1997/ 
wget -r ftp://prism.nacse.org/daily/tmin/1998/ 
wget -r ftp://prism.nacse.org/daily/tmin/1999/ 
wget -r ftp://prism.nacse.org/daily/tmin/2000/
wget -r ftp://prism.nacse.org/daily/tmin/2001/
wget -r ftp://prism.nacse.org/daily/tmin/2002/
wget -r ftp://prism.nacse.org/daily/tmin/2003/
wget -r ftp://prism.nacse.org/daily/tmin/2004/
wget -r ftp://prism.nacse.org/daily/tmin/2005/
wget -r ftp://prism.nacse.org/daily/tmin/2006/
wget -r ftp://prism.nacse.org/daily/tmin/2007/ 
wget -r ftp://prism.nacse.org/daily/tmin/2008/
wget -r ftp://prism.nacse.org/daily/tmin/2009/
wget -r ftp://prism.nacse.org/daily/tmin/2010/
wget -r ftp://prism.nacse.org/daily/tmin/2011/
wget -r ftp://prism.nacse.org/daily/tmin/2012/ 
wget -r ftp://prism.nacse.org/daily/tmin/2013/ 
wget -r ftp://prism.nacse.org/daily/tmin/2014/ 
wget -r ftp://prism.nacse.org/daily/tmin/2015/ 
wget -r ftp://prism.nacse.org/daily/tmin/2016/ 
wget -r ftp://prism.nacse.org/daily/tmin/2017/ 
wget -r ftp://prism.nacse.org/daily/tmin/2018/ 
wget -r ftp://prism.nacse.org/daily/tmin/2019/ 
wget -r ftp://prism.nacse.org/daily/tmin/2020/ 
wget -r ftp://prism.nacse.org/daily/tmin/2021/ 

wget -r ftp://prism.nacse.org/daily/tmax/1980/ 
wget -r ftp://prism.nacse.org/daily/tmax/1981/
wget -r ftp://prism.nacse.org/daily/tmax/1982/ 
wget -r ftp://prism.nacse.org/daily/tmax/1983/ 
wget -r ftp://prism.nacse.org/daily/tmax/1984/ 
wget -r ftp://prism.nacse.org/daily/tmax/1985/ 
wget -r ftp://prism.nacse.org/daily/tmax/1986/ 
wget -r ftp://prism.nacse.org/daily/tmax/1987/ 
wget -r ftp://prism.nacse.org/daily/tmax/1988/ 
wget -r ftp://prism.nacse.org/daily/tmax/1989/ 
wget -r ftp://prism.nacse.org/daily/tmax/1990/ 
wget -r ftp://prism.nacse.org/daily/tmax/1991/
wget -r ftp://prism.nacse.org/daily/tmax/1992/ 
wget -r ftp://prism.nacse.org/daily/tmax/1993/ 
wget -r ftp://prism.nacse.org/daily/tmax/1994/ 
wget -r ftp://prism.nacse.org/daily/tmax/1995/ 
wget -r ftp://prism.nacse.org/daily/tmax/1996/ 
wget -r ftp://prism.nacse.org/daily/tmax/1997/ 
wget -r ftp://prism.nacse.org/daily/tmax/1998/ 
wget -r ftp://prism.nacse.org/daily/tmax/1999/ 
wget -r ftp://prism.nacse.org/daily/tmax/2000/
wget -r ftp://prism.nacse.org/daily/tmax/2001/
wget -r ftp://prism.nacse.org/daily/tmax/2002/
wget -r ftp://prism.nacse.org/daily/tmax/2003/
wget -r ftp://prism.nacse.org/daily/tmax/2004/
wget -r ftp://prism.nacse.org/daily/tmax/2005/
wget -r ftp://prism.nacse.org/daily/tmax/2006/
wget -r ftp://prism.nacse.org/daily/tmax/2007/ 
wget -r ftp://prism.nacse.org/daily/tmax/2008/
wget -r ftp://prism.nacse.org/daily/tmax/2009/
wget -r ftp://prism.nacse.org/daily/tmax/2010/
wget -r ftp://prism.nacse.org/daily/tmax/2011/
wget -r ftp://prism.nacse.org/daily/tmax/2012/ 
wget -r ftp://prism.nacse.org/daily/tmax/2013/ 
wget -r ftp://prism.nacse.org/daily/tmax/2014/ 
wget -r ftp://prism.nacse.org/daily/tmax/2015/ 
wget -r ftp://prism.nacse.org/daily/tmax/2016/ 
wget -r ftp://prism.nacse.org/daily/tmax/2017/ 
wget -r ftp://prism.nacse.org/daily/tmax/2018/ 
wget -r ftp://prism.nacse.org/daily/tmax/2019/ 
wget -r ftp://prism.nacse.org/daily/tmax/2020/ 
wget -r ftp://prism.nacse.org/daily/tmax/2021/ 

wget -r ftp://prism.nacse.org/daily/ppt/1980/ 
wget -r ftp://prism.nacse.org/daily/ppt/1981/
wget -r ftp://prism.nacse.org/daily/ppt/1982/ 
wget -r ftp://prism.nacse.org/daily/ppt/1983/ 
wget -r ftp://prism.nacse.org/daily/ppt/1984/ 
wget -r ftp://prism.nacse.org/daily/ppt/1985/ 
wget -r ftp://prism.nacse.org/daily/ppt/1986/ 
wget -r ftp://prism.nacse.org/daily/ppt/1987/ 
wget -r ftp://prism.nacse.org/daily/ppt/1988/ 
wget -r ftp://prism.nacse.org/daily/ppt/1989/ 
wget -r ftp://prism.nacse.org/daily/ppt/1990/ 
wget -r ftp://prism.nacse.org/daily/ppt/1991/
wget -r ftp://prism.nacse.org/daily/ppt/1992/ 
wget -r ftp://prism.nacse.org/daily/ppt/1993/ 
wget -r ftp://prism.nacse.org/daily/ppt/1994/ 
wget -r ftp://prism.nacse.org/daily/ppt/1995/ 
wget -r ftp://prism.nacse.org/daily/ppt/1996/ 
wget -r ftp://prism.nacse.org/daily/ppt/1997/ 
wget -r ftp://prism.nacse.org/daily/ppt/1998/ 
wget -r ftp://prism.nacse.org/daily/ppt/1999/ 
wget -r ftp://prism.nacse.org/daily/ppt/2000/
wget -r ftp://prism.nacse.org/daily/ppt/2001/
wget -r ftp://prism.nacse.org/daily/ppt/2002/
wget -r ftp://prism.nacse.org/daily/ppt/2003/
wget -r ftp://prism.nacse.org/daily/ppt/2004/
wget -r ftp://prism.nacse.org/daily/ppt/2005/
wget -r ftp://prism.nacse.org/daily/ppt/2006/
wget -r ftp://prism.nacse.org/daily/ppt/2007/ 
wget -r ftp://prism.nacse.org/daily/ppt/2008/
wget -r ftp://prism.nacse.org/daily/ppt/2009/
wget -r ftp://prism.nacse.org/daily/ppt/2010/
wget -r ftp://prism.nacse.org/daily/ppt/2011/
wget -r ftp://prism.nacse.org/daily/ppt/2012/ 
wget -r ftp://prism.nacse.org/daily/ppt/2013/ 
wget -r ftp://prism.nacse.org/daily/ppt/2014/ 
wget -r ftp://prism.nacse.org/daily/ppt/2015/ 
wget -r ftp://prism.nacse.org/daily/ppt/2016/ 
wget -r ftp://prism.nacse.org/daily/ppt/2017/ 
wget -r ftp://prism.nacse.org/daily/ppt/2018/ 
wget -r ftp://prism.nacse.org/daily/ppt/2019/ 
wget -r ftp://prism.nacse.org/daily/ppt/2020/ 
wget -r ftp://prism.nacse.org/daily/ppt/2021/ 
 



wget -r ftp://prism.nacse.org/monthly/tmin/1895/
wget -r ftp://prism.nacse.org/monthly/tmin/1896/
wget -r ftp://prism.nacse.org/monthly/tmin/1897/
wget -r ftp://prism.nacse.org/monthly/tmin/1898/
wget -r ftp://prism.nacse.org/monthly/tmin/1899/
wget -r ftp://prism.nacse.org/monthly/tmin/1900/
wget -r ftp://prism.nacse.org/monthly/tmin/1901/
wget -r ftp://prism.nacse.org/monthly/tmin/1902/
wget -r ftp://prism.nacse.org/monthly/tmin/1903/
wget -r ftp://prism.nacse.org/monthly/tmin/1904/
wget -r ftp://prism.nacse.org/monthly/tmin/1905/
wget -r ftp://prism.nacse.org/monthly/tmin/1906/
wget -r ftp://prism.nacse.org/monthly/tmin/1907/
wget -r ftp://prism.nacse.org/monthly/tmin/1908/
wget -r ftp://prism.nacse.org/monthly/tmin/1909/
wget -r ftp://prism.nacse.org/monthly/tmin/1910/
wget -r ftp://prism.nacse.org/monthly/tmin/1911/
wget -r ftp://prism.nacse.org/monthly/tmin/1912/
wget -r ftp://prism.nacse.org/monthly/tmin/1913/
wget -r ftp://prism.nacse.org/monthly/tmin/1914/
wget -r ftp://prism.nacse.org/monthly/tmin/1915/
wget -r ftp://prism.nacse.org/monthly/tmin/1916/
wget -r ftp://prism.nacse.org/monthly/tmin/1917/
wget -r ftp://prism.nacse.org/monthly/tmin/1918/
wget -r ftp://prism.nacse.org/monthly/tmin/1919/
wget -r ftp://prism.nacse.org/monthly/tmin/1920/
wget -r ftp://prism.nacse.org/monthly/tmin/1921/
wget -r ftp://prism.nacse.org/monthly/tmin/1922/
wget -r ftp://prism.nacse.org/monthly/tmin/1923/
wget -r ftp://prism.nacse.org/monthly/tmin/1924/
wget -r ftp://prism.nacse.org/monthly/tmin/1925/
wget -r ftp://prism.nacse.org/monthly/tmin/1926/
wget -r ftp://prism.nacse.org/monthly/tmin/1927/
wget -r ftp://prism.nacse.org/monthly/tmin/1928/
wget -r ftp://prism.nacse.org/monthly/tmin/1929/
wget -r ftp://prism.nacse.org/monthly/tmin/1930/
wget -r ftp://prism.nacse.org/monthly/tmin/1931/
wget -r ftp://prism.nacse.org/monthly/tmin/1932/
wget -r ftp://prism.nacse.org/monthly/tmin/1933/
wget -r ftp://prism.nacse.org/monthly/tmin/1934/
wget -r ftp://prism.nacse.org/monthly/tmin/1935/
wget -r ftp://prism.nacse.org/monthly/tmin/1936/
wget -r ftp://prism.nacse.org/monthly/tmin/1937/
wget -r ftp://prism.nacse.org/monthly/tmin/1938/
wget -r ftp://prism.nacse.org/monthly/tmin/1939/
wget -r ftp://prism.nacse.org/monthly/tmin/1940/
wget -r ftp://prism.nacse.org/monthly/tmin/1941/
wget -r ftp://prism.nacse.org/monthly/tmin/1942/
wget -r ftp://prism.nacse.org/monthly/tmin/1943/
wget -r ftp://prism.nacse.org/monthly/tmin/1944/
wget -r ftp://prism.nacse.org/monthly/tmin/1945/
wget -r ftp://prism.nacse.org/monthly/tmin/1946/
wget -r ftp://prism.nacse.org/monthly/tmin/1947/
wget -r ftp://prism.nacse.org/monthly/tmin/1948/
wget -r ftp://prism.nacse.org/monthly/tmin/1949/
wget -r ftp://prism.nacse.org/monthly/tmin/1950/
wget -r ftp://prism.nacse.org/monthly/tmin/1951/
wget -r ftp://prism.nacse.org/monthly/tmin/1952/
wget -r ftp://prism.nacse.org/monthly/tmin/1953/
wget -r ftp://prism.nacse.org/monthly/tmin/1954/
wget -r ftp://prism.nacse.org/monthly/tmin/1955/
wget -r ftp://prism.nacse.org/monthly/tmin/1956/
wget -r ftp://prism.nacse.org/monthly/tmin/1957/
wget -r ftp://prism.nacse.org/monthly/tmin/1958/
wget -r ftp://prism.nacse.org/monthly/tmin/1959/
wget -r ftp://prism.nacse.org/monthly/tmin/1960/
wget -r ftp://prism.nacse.org/monthly/tmin/1961/
wget -r ftp://prism.nacse.org/monthly/tmin/1962/
wget -r ftp://prism.nacse.org/monthly/tmin/1963/
wget -r ftp://prism.nacse.org/monthly/tmin/1964/
wget -r ftp://prism.nacse.org/monthly/tmin/1965/
wget -r ftp://prism.nacse.org/monthly/tmin/1966/
wget -r ftp://prism.nacse.org/monthly/tmin/1967/
wget -r ftp://prism.nacse.org/monthly/tmin/1968/
wget -r ftp://prism.nacse.org/monthly/tmin/1969/
wget -r ftp://prism.nacse.org/monthly/tmin/1970/
wget -r ftp://prism.nacse.org/monthly/tmin/1971/
wget -r ftp://prism.nacse.org/monthly/tmin/1972/
wget -r ftp://prism.nacse.org/monthly/tmin/1973/
wget -r ftp://prism.nacse.org/monthly/tmin/1974/
wget -r ftp://prism.nacse.org/monthly/tmin/1975/
wget -r ftp://prism.nacse.org/monthly/tmin/1976/
wget -r ftp://prism.nacse.org/monthly/tmin/1977/
wget -r ftp://prism.nacse.org/monthly/tmin/1978/
wget -r ftp://prism.nacse.org/monthly/tmin/1979/
wget -r ftp://prism.nacse.org/monthly/tmin/1980/
wget -r ftp://prism.nacse.org/monthly/tmin/1981/
wget -r ftp://prism.nacse.org/monthly/tmin/1982/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1983/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1984/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1985/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1986/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1987/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1988/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1989/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1990/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1991/
wget -r ftp://prism.nacse.org/monthly/tmin/1992/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1993/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1994/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1995/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1996/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1997/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1998/ 
wget -r ftp://prism.nacse.org/monthly/tmin/1999/ 
wget -r ftp://prism.nacse.org/monthly/tmin/2000/
wget -r ftp://prism.nacse.org/monthly/tmin/2001/
wget -r ftp://prism.nacse.org/monthly/tmin/2002/
wget -r ftp://prism.nacse.org/monthly/tmin/2003/
wget -r ftp://prism.nacse.org/monthly/tmin/2004/
wget -r ftp://prism.nacse.org/monthly/tmin/2005/
wget -r ftp://prism.nacse.org/monthly/tmin/2006/
wget -r ftp://prism.nacse.org/monthly/tmin/2007/ 
wget -r ftp://prism.nacse.org/monthly/tmin/2008/
wget -r ftp://prism.nacse.org/monthly/tmin/2009/
wget -r ftp://prism.nacse.org/monthly/tmin/2010/
wget -r ftp://prism.nacse.org/monthly/tmin/2011/
wget -r ftp://prism.nacse.org/monthly/tmin/2012/ 
wget -r ftp://prism.nacse.org/monthly/tmin/2013/ 
wget -r ftp://prism.nacse.org/monthly/tmin/2014/ 
wget -r ftp://prism.nacse.org/monthly/tmin/2015/ 
wget -r ftp://prism.nacse.org/monthly/tmin/2016/ 
wget -r ftp://prism.nacse.org/monthly/tmin/2017/ 
wget -r ftp://prism.nacse.org/monthly/tmin/2018/ 
wget -r ftp://prism.nacse.org/monthly/tmin/2019/ 
wget -r ftp://prism.nacse.org/monthly/tmin/2020/ 
wget -r ftp://prism.nacse.org/monthly/tmin/2021/ 



wget -r ftp://prism.nacse.org/monthly/tmax/1895/
wget -r ftp://prism.nacse.org/monthly/tmax/1896/
wget -r ftp://prism.nacse.org/monthly/tmax/1897/
wget -r ftp://prism.nacse.org/monthly/tmax/1898/
wget -r ftp://prism.nacse.org/monthly/tmax/1899/
wget -r ftp://prism.nacse.org/monthly/tmax/1900/
wget -r ftp://prism.nacse.org/monthly/tmax/1901/
wget -r ftp://prism.nacse.org/monthly/tmax/1902/
wget -r ftp://prism.nacse.org/monthly/tmax/1903/
wget -r ftp://prism.nacse.org/monthly/tmax/1904/
wget -r ftp://prism.nacse.org/monthly/tmax/1905/
wget -r ftp://prism.nacse.org/monthly/tmax/1906/
wget -r ftp://prism.nacse.org/monthly/tmax/1907/
wget -r ftp://prism.nacse.org/monthly/tmax/1908/
wget -r ftp://prism.nacse.org/monthly/tmax/1909/
wget -r ftp://prism.nacse.org/monthly/tmax/1910/
wget -r ftp://prism.nacse.org/monthly/tmax/1911/
wget -r ftp://prism.nacse.org/monthly/tmax/1912/
wget -r ftp://prism.nacse.org/monthly/tmax/1913/
wget -r ftp://prism.nacse.org/monthly/tmax/1914/
wget -r ftp://prism.nacse.org/monthly/tmax/1915/
wget -r ftp://prism.nacse.org/monthly/tmax/1916/
wget -r ftp://prism.nacse.org/monthly/tmax/1917/
wget -r ftp://prism.nacse.org/monthly/tmax/1918/
wget -r ftp://prism.nacse.org/monthly/tmax/1919/
wget -r ftp://prism.nacse.org/monthly/tmax/1920/
wget -r ftp://prism.nacse.org/monthly/tmax/1921/
wget -r ftp://prism.nacse.org/monthly/tmax/1922/
wget -r ftp://prism.nacse.org/monthly/tmax/1923/
wget -r ftp://prism.nacse.org/monthly/tmax/1924/
wget -r ftp://prism.nacse.org/monthly/tmax/1925/
wget -r ftp://prism.nacse.org/monthly/tmax/1926/
wget -r ftp://prism.nacse.org/monthly/tmax/1927/
wget -r ftp://prism.nacse.org/monthly/tmax/1928/
wget -r ftp://prism.nacse.org/monthly/tmax/1929/
wget -r ftp://prism.nacse.org/monthly/tmax/1930/
wget -r ftp://prism.nacse.org/monthly/tmax/1931/
wget -r ftp://prism.nacse.org/monthly/tmax/1932/
wget -r ftp://prism.nacse.org/monthly/tmax/1933/
wget -r ftp://prism.nacse.org/monthly/tmax/1934/
wget -r ftp://prism.nacse.org/monthly/tmax/1935/
wget -r ftp://prism.nacse.org/monthly/tmax/1936/
wget -r ftp://prism.nacse.org/monthly/tmax/1937/
wget -r ftp://prism.nacse.org/monthly/tmax/1938/
wget -r ftp://prism.nacse.org/monthly/tmax/1939/
wget -r ftp://prism.nacse.org/monthly/tmax/1940/
wget -r ftp://prism.nacse.org/monthly/tmax/1941/
wget -r ftp://prism.nacse.org/monthly/tmax/1942/
wget -r ftp://prism.nacse.org/monthly/tmax/1943/
wget -r ftp://prism.nacse.org/monthly/tmax/1944/
wget -r ftp://prism.nacse.org/monthly/tmax/1945/
wget -r ftp://prism.nacse.org/monthly/tmax/1946/
wget -r ftp://prism.nacse.org/monthly/tmax/1947/
wget -r ftp://prism.nacse.org/monthly/tmax/1948/
wget -r ftp://prism.nacse.org/monthly/tmax/1949/
wget -r ftp://prism.nacse.org/monthly/tmax/1950/
wget -r ftp://prism.nacse.org/monthly/tmax/1951/
wget -r ftp://prism.nacse.org/monthly/tmax/1952/
wget -r ftp://prism.nacse.org/monthly/tmax/1953/
wget -r ftp://prism.nacse.org/monthly/tmax/1954/
wget -r ftp://prism.nacse.org/monthly/tmax/1955/
wget -r ftp://prism.nacse.org/monthly/tmax/1956/
wget -r ftp://prism.nacse.org/monthly/tmax/1957/
wget -r ftp://prism.nacse.org/monthly/tmax/1958/
wget -r ftp://prism.nacse.org/monthly/tmax/1959/
wget -r ftp://prism.nacse.org/monthly/tmax/1960/
wget -r ftp://prism.nacse.org/monthly/tmax/1961/
wget -r ftp://prism.nacse.org/monthly/tmax/1962/
wget -r ftp://prism.nacse.org/monthly/tmax/1963/
wget -r ftp://prism.nacse.org/monthly/tmax/1964/
wget -r ftp://prism.nacse.org/monthly/tmax/1965/
wget -r ftp://prism.nacse.org/monthly/tmax/1966/
wget -r ftp://prism.nacse.org/monthly/tmax/1967/
wget -r ftp://prism.nacse.org/monthly/tmax/1968/
wget -r ftp://prism.nacse.org/monthly/tmax/1969/
wget -r ftp://prism.nacse.org/monthly/tmax/1970/
wget -r ftp://prism.nacse.org/monthly/tmax/1971/
wget -r ftp://prism.nacse.org/monthly/tmax/1972/
wget -r ftp://prism.nacse.org/monthly/tmax/1973/
wget -r ftp://prism.nacse.org/monthly/tmax/1974/
wget -r ftp://prism.nacse.org/monthly/tmax/1975/
wget -r ftp://prism.nacse.org/monthly/tmax/1976/
wget -r ftp://prism.nacse.org/monthly/tmax/1977/
wget -r ftp://prism.nacse.org/monthly/tmax/1978/
wget -r ftp://prism.nacse.org/monthly/tmax/1979/
wget -r ftp://prism.nacse.org/monthly/tmax/1980/
wget -r ftp://prism.nacse.org/monthly/tmax/1981/
wget -r ftp://prism.nacse.org/monthly/tmax/1982/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1983/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1984/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1985/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1986/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1987/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1988/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1989/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1990/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1991/
wget -r ftp://prism.nacse.org/monthly/tmax/1992/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1993/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1994/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1995/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1996/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1997/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1998/ 
wget -r ftp://prism.nacse.org/monthly/tmax/1999/ 
wget -r ftp://prism.nacse.org/monthly/tmax/2000/
wget -r ftp://prism.nacse.org/monthly/tmax/2001/
wget -r ftp://prism.nacse.org/monthly/tmax/2002/
wget -r ftp://prism.nacse.org/monthly/tmax/2003/
wget -r ftp://prism.nacse.org/monthly/tmax/2004/
wget -r ftp://prism.nacse.org/monthly/tmax/2005/
wget -r ftp://prism.nacse.org/monthly/tmax/2006/
wget -r ftp://prism.nacse.org/monthly/tmax/2007/ 
wget -r ftp://prism.nacse.org/monthly/tmax/2008/
wget -r ftp://prism.nacse.org/monthly/tmax/2009/
wget -r ftp://prism.nacse.org/monthly/tmax/2010/
wget -r ftp://prism.nacse.org/monthly/tmax/2011/
wget -r ftp://prism.nacse.org/monthly/tmax/2012/ 
wget -r ftp://prism.nacse.org/monthly/tmax/2013/ 
wget -r ftp://prism.nacse.org/monthly/tmax/2014/ 
wget -r ftp://prism.nacse.org/monthly/tmax/2015/ 
wget -r ftp://prism.nacse.org/monthly/tmax/2016/ 
wget -r ftp://prism.nacse.org/monthly/tmax/2017/ 
wget -r ftp://prism.nacse.org/monthly/tmax/2018/ 
wget -r ftp://prism.nacse.org/monthly/tmax/2019/ 
wget -r ftp://prism.nacse.org/monthly/tmax/2020/ 
wget -r ftp://prism.nacse.org/monthly/tmax/2021/ 



wget -r ftp://prism.nacse.org/monthly/ppt/1895/
wget -r ftp://prism.nacse.org/monthly/ppt/1896/
wget -r ftp://prism.nacse.org/monthly/ppt/1897/
wget -r ftp://prism.nacse.org/monthly/ppt/1898/
wget -r ftp://prism.nacse.org/monthly/ppt/1899/
wget -r ftp://prism.nacse.org/monthly/ppt/1900/
wget -r ftp://prism.nacse.org/monthly/ppt/1901/
wget -r ftp://prism.nacse.org/monthly/ppt/1902/
wget -r ftp://prism.nacse.org/monthly/ppt/1903/
wget -r ftp://prism.nacse.org/monthly/ppt/1904/
wget -r ftp://prism.nacse.org/monthly/ppt/1905/
wget -r ftp://prism.nacse.org/monthly/ppt/1906/
wget -r ftp://prism.nacse.org/monthly/ppt/1907/
wget -r ftp://prism.nacse.org/monthly/ppt/1908/
wget -r ftp://prism.nacse.org/monthly/ppt/1909/
wget -r ftp://prism.nacse.org/monthly/ppt/1910/
wget -r ftp://prism.nacse.org/monthly/ppt/1911/
wget -r ftp://prism.nacse.org/monthly/ppt/1912/
wget -r ftp://prism.nacse.org/monthly/ppt/1913/
wget -r ftp://prism.nacse.org/monthly/ppt/1914/
wget -r ftp://prism.nacse.org/monthly/ppt/1915/
wget -r ftp://prism.nacse.org/monthly/ppt/1916/
wget -r ftp://prism.nacse.org/monthly/ppt/1917/
wget -r ftp://prism.nacse.org/monthly/ppt/1918/
wget -r ftp://prism.nacse.org/monthly/ppt/1919/
wget -r ftp://prism.nacse.org/monthly/ppt/1920/
wget -r ftp://prism.nacse.org/monthly/ppt/1921/
wget -r ftp://prism.nacse.org/monthly/ppt/1922/
wget -r ftp://prism.nacse.org/monthly/ppt/1923/
wget -r ftp://prism.nacse.org/monthly/ppt/1924/
wget -r ftp://prism.nacse.org/monthly/ppt/1925/
wget -r ftp://prism.nacse.org/monthly/ppt/1926/
wget -r ftp://prism.nacse.org/monthly/ppt/1927/
wget -r ftp://prism.nacse.org/monthly/ppt/1928/
wget -r ftp://prism.nacse.org/monthly/ppt/1929/
wget -r ftp://prism.nacse.org/monthly/ppt/1930/
wget -r ftp://prism.nacse.org/monthly/ppt/1931/
wget -r ftp://prism.nacse.org/monthly/ppt/1932/
wget -r ftp://prism.nacse.org/monthly/ppt/1933/
wget -r ftp://prism.nacse.org/monthly/ppt/1934/
wget -r ftp://prism.nacse.org/monthly/ppt/1935/
wget -r ftp://prism.nacse.org/monthly/ppt/1936/
wget -r ftp://prism.nacse.org/monthly/ppt/1937/
wget -r ftp://prism.nacse.org/monthly/ppt/1938/
wget -r ftp://prism.nacse.org/monthly/ppt/1939/
wget -r ftp://prism.nacse.org/monthly/ppt/1940/
wget -r ftp://prism.nacse.org/monthly/ppt/1941/
wget -r ftp://prism.nacse.org/monthly/ppt/1942/
wget -r ftp://prism.nacse.org/monthly/ppt/1943/
wget -r ftp://prism.nacse.org/monthly/ppt/1944/
wget -r ftp://prism.nacse.org/monthly/ppt/1945/
wget -r ftp://prism.nacse.org/monthly/ppt/1946/
wget -r ftp://prism.nacse.org/monthly/ppt/1947/
wget -r ftp://prism.nacse.org/monthly/ppt/1948/
wget -r ftp://prism.nacse.org/monthly/ppt/1949/
wget -r ftp://prism.nacse.org/monthly/ppt/1950/
wget -r ftp://prism.nacse.org/monthly/ppt/1951/
wget -r ftp://prism.nacse.org/monthly/ppt/1952/
wget -r ftp://prism.nacse.org/monthly/ppt/1953/
wget -r ftp://prism.nacse.org/monthly/ppt/1954/
wget -r ftp://prism.nacse.org/monthly/ppt/1955/
wget -r ftp://prism.nacse.org/monthly/ppt/1956/
wget -r ftp://prism.nacse.org/monthly/ppt/1957/
wget -r ftp://prism.nacse.org/monthly/ppt/1958/
wget -r ftp://prism.nacse.org/monthly/ppt/1959/
wget -r ftp://prism.nacse.org/monthly/ppt/1960/
wget -r ftp://prism.nacse.org/monthly/ppt/1961/
wget -r ftp://prism.nacse.org/monthly/ppt/1962/
wget -r ftp://prism.nacse.org/monthly/ppt/1963/
wget -r ftp://prism.nacse.org/monthly/ppt/1964/
wget -r ftp://prism.nacse.org/monthly/ppt/1965/
wget -r ftp://prism.nacse.org/monthly/ppt/1966/
wget -r ftp://prism.nacse.org/monthly/ppt/1967/
wget -r ftp://prism.nacse.org/monthly/ppt/1968/
wget -r ftp://prism.nacse.org/monthly/ppt/1969/
wget -r ftp://prism.nacse.org/monthly/ppt/1970/
wget -r ftp://prism.nacse.org/monthly/ppt/1971/
wget -r ftp://prism.nacse.org/monthly/ppt/1972/
wget -r ftp://prism.nacse.org/monthly/ppt/1973/
wget -r ftp://prism.nacse.org/monthly/ppt/1974/
wget -r ftp://prism.nacse.org/monthly/ppt/1975/
wget -r ftp://prism.nacse.org/monthly/ppt/1976/
wget -r ftp://prism.nacse.org/monthly/ppt/1977/
wget -r ftp://prism.nacse.org/monthly/ppt/1978/
wget -r ftp://prism.nacse.org/monthly/ppt/1979/
wget -r ftp://prism.nacse.org/monthly/ppt/1980/
wget -r ftp://prism.nacse.org/monthly/ppt/1981/
wget -r ftp://prism.nacse.org/monthly/ppt/1982/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1983/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1984/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1985/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1986/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1987/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1988/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1989/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1990/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1991/
wget -r ftp://prism.nacse.org/monthly/ppt/1992/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1993/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1994/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1995/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1996/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1997/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1998/ 
wget -r ftp://prism.nacse.org/monthly/ppt/1999/ 
wget -r ftp://prism.nacse.org/monthly/ppt/2000/
wget -r ftp://prism.nacse.org/monthly/ppt/2001/
wget -r ftp://prism.nacse.org/monthly/ppt/2002/
wget -r ftp://prism.nacse.org/monthly/ppt/2003/
wget -r ftp://prism.nacse.org/monthly/ppt/2004/
wget -r ftp://prism.nacse.org/monthly/ppt/2005/
wget -r ftp://prism.nacse.org/monthly/ppt/2006/
wget -r ftp://prism.nacse.org/monthly/ppt/2007/ 
wget -r ftp://prism.nacse.org/monthly/ppt/2008/
wget -r ftp://prism.nacse.org/monthly/ppt/2009/
wget -r ftp://prism.nacse.org/monthly/ppt/2010/
wget -r ftp://prism.nacse.org/monthly/ppt/2011/
wget -r ftp://prism.nacse.org/monthly/ppt/2012/ 
wget -r ftp://prism.nacse.org/monthly/ppt/2013/ 
wget -r ftp://prism.nacse.org/monthly/ppt/2014/ 
wget -r ftp://prism.nacse.org/monthly/ppt/2015/ 
wget -r ftp://prism.nacse.org/monthly/ppt/2016/ 
wget -r ftp://prism.nacse.org/monthly/ppt/2017/ 
wget -r ftp://prism.nacse.org/monthly/ppt/2018/ 
wget -r ftp://prism.nacse.org/monthly/ppt/2019/ 
wget -r ftp://prism.nacse.org/monthly/ppt/2020/ 
wget -r ftp://prism.nacse.org/monthly/ppt/2021/ 


exec bash