#!/bin/bash
wget -r ftp://prism.nacse.org/daily/tmin/1980/ 
wget -r ftp://prism.nacse.org/daily/tmin/1981/
wget -r ftp://prism.nacse.org/daily/tmin/1982/ 
wget -r ftp://prism.nacse.org/daily/tmin/1983/ 
wget -r ftp://prism.nacse.org/daily/tmin/1984/ 
wget -r ftp://prism.nacse.org/daily/tmin/1985/ 
wget -r ftp://prism.nacse.org/daily/tmin/1986/ 
wget -r ftp://prism.nacse.org/daily/tmin/1987/ 
wget -r ftp://prism.nacse.org/daily/tmin/1988/ 
wget -r ftp://prism.nacse.org/daily/tmin/1989/ 
wget -r ftp://prism.nacse.org/daily/tmin/1990/ 
wget -r ftp://prism.nacse.org/daily/tmin/1991/
wget -r ftp://prism.nacse.org/daily/tmin/1992/ 
wget -r ftp://prism.nacse.org/daily/tmin/1993/ 
wget -r ftp://prism.nacse.org/daily/tmin/1994/ 
wget -r ftp://prism.nacse.org/daily/tmin/1995/ 
wget -r ftp://prism.nacse.org/daily/tmin/1996/ 
wget -r ftp://prism.nacse.org/daily/tmin/1997/ 
wget -r ftp://prism.nacse.org/daily/tmin/1998/ 
wget -r ftp://prism.nacse.org/daily/tmin/1999/ 
wget -r ftp://prism.nacse.org/daily/tmin/2000/
wget -r ftp://prism.nacse.org/daily/tmin/2001/
wget -r ftp://prism.nacse.org/daily/tmin/2002/
wget -r ftp://prism.nacse.org/daily/tmin/2003/
wget -r ftp://prism.nacse.org/daily/tmin/2004/
wget -r ftp://prism.nacse.org/daily/tmin/2005/
wget -r ftp://prism.nacse.org/daily/tmin/2006/
wget -r ftp://prism.nacse.org/daily/tmin/2007/ 
wget -r ftp://prism.nacse.org/daily/tmin/2008/
wget -r ftp://prism.nacse.org/daily/tmin/2009/
wget -r ftp://prism.nacse.org/daily/tmin/2010/
wget -r ftp://prism.nacse.org/daily/tmin/2011/
wget -r ftp://prism.nacse.org/daily/tmin/2012/ 
wget -r ftp://prism.nacse.org/daily/tmin/2013/ 
wget -r ftp://prism.nacse.org/daily/tmin/2014/ 
wget -r ftp://prism.nacse.org/daily/tmin/2015/ 
wget -r ftp://prism.nacse.org/daily/tmin/2016/ 
wget -r ftp://prism.nacse.org/daily/tmin/2017/ 
wget -r ftp://prism.nacse.org/daily/tmin/2018/ 
wget -r ftp://prism.nacse.org/daily/tmin/2019/ 
wget -r ftp://prism.nacse.org/daily/tmin/2020/ 
wget -r ftp://prism.nacse.org/daily/tmin/2021/ 

wget -r ftp://prism.nacse.org/daily/tmax/1980/ 
wget -r ftp://prism.nacse.org/daily/tmax/1981/
wget -r ftp://prism.nacse.org/daily/tmax/1982/ 
wget -r ftp://prism.nacse.org/daily/tmax/1983/ 
wget -r ftp://prism.nacse.org/daily/tmax/1984/ 
wget -r ftp://prism.nacse.org/daily/tmax/1985/ 
wget -r ftp://prism.nacse.org/daily/tmax/1986/ 
wget -r ftp://prism.nacse.org/daily/tmax/1987/ 
wget -r ftp://prism.nacse.org/daily/tmax/1988/ 
wget -r ftp://prism.nacse.org/daily/tmax/1989/ 
wget -r ftp://prism.nacse.org/daily/tmax/1990/ 
wget -r ftp://prism.nacse.org/daily/tmax/1991/
wget -r ftp://prism.nacse.org/daily/tmax/1992/ 
wget -r ftp://prism.nacse.org/daily/tmax/1993/ 
wget -r ftp://prism.nacse.org/daily/tmax/1994/ 
wget -r ftp://prism.nacse.org/daily/tmax/1995/ 
wget -r ftp://prism.nacse.org/daily/tmax/1996/ 
wget -r ftp://prism.nacse.org/daily/tmax/1997/ 
wget -r ftp://prism.nacse.org/daily/tmax/1998/ 
wget -r ftp://prism.nacse.org/daily/tmax/1999/ 
wget -r ftp://prism.nacse.org/daily/tmax/2000/
wget -r ftp://prism.nacse.org/daily/tmax/2001/
wget -r ftp://prism.nacse.org/daily/tmax/2002/
wget -r ftp://prism.nacse.org/daily/tmax/2003/
wget -r ftp://prism.nacse.org/daily/tmax/2004/
wget -r ftp://prism.nacse.org/daily/tmax/2005/
wget -r ftp://prism.nacse.org/daily/tmax/2006/
wget -r ftp://prism.nacse.org/daily/tmax/2007/ 
wget -r ftp://prism.nacse.org/daily/tmax/2008/
wget -r ftp://prism.nacse.org/daily/tmax/2009/
wget -r ftp://prism.nacse.org/daily/tmax/2010/
wget -r ftp://prism.nacse.org/daily/tmax/2011/
wget -r ftp://prism.nacse.org/daily/tmax/2012/ 
wget -r ftp://prism.nacse.org/daily/tmax/2013/ 
wget -r ftp://prism.nacse.org/daily/tmax/2014/ 
wget -r ftp://prism.nacse.org/daily/tmax/2015/ 
wget -r ftp://prism.nacse.org/daily/tmax/2016/ 
wget -r ftp://prism.nacse.org/daily/tmax/2017/ 
wget -r ftp://prism.nacse.org/daily/tmax/2018/ 
wget -r ftp://prism.nacse.org/daily/tmax/2019/ 
wget -r ftp://prism.nacse.org/daily/tmax/2020/ 
wget -r ftp://prism.nacse.org/daily/tmax/2021/ 

wget -r ftp://prism.nacse.org/daily/ppt/1980/ 
wget -r ftp://prism.nacse.org/daily/ppt/1981/
wget -r ftp://prism.nacse.org/daily/ppt/1982/ 
wget -r ftp://prism.nacse.org/daily/ppt/1983/ 
wget -r ftp://prism.nacse.org/daily/ppt/1984/ 
wget -r ftp://prism.nacse.org/daily/ppt/1985/ 
wget -r ftp://prism.nacse.org/daily/ppt/1986/ 
wget -r ftp://prism.nacse.org/daily/ppt/1987/ 
wget -r ftp://prism.nacse.org/daily/ppt/1988/ 
wget -r ftp://prism.nacse.org/daily/ppt/1989/ 
wget -r ftp://prism.nacse.org/daily/ppt/1990/ 
wget -r ftp://prism.nacse.org/daily/ppt/1991/
wget -r ftp://prism.nacse.org/daily/ppt/1992/ 
wget -r ftp://prism.nacse.org/daily/ppt/1993/ 
wget -r ftp://prism.nacse.org/daily/ppt/1994/ 
wget -r ftp://prism.nacse.org/daily/ppt/1995/ 
wget -r ftp://prism.nacse.org/daily/ppt/1996/ 
wget -r ftp://prism.nacse.org/daily/ppt/1997/ 
wget -r ftp://prism.nacse.org/daily/ppt/1998/ 
wget -r ftp://prism.nacse.org/daily/ppt/1999/ 
wget -r ftp://prism.nacse.org/daily/ppt/2000/
wget -r ftp://prism.nacse.org/daily/ppt/2001/
wget -r ftp://prism.nacse.org/daily/ppt/2002/
wget -r ftp://prism.nacse.org/daily/ppt/2003/
wget -r ftp://prism.nacse.org/daily/ppt/2004/
wget -r ftp://prism.nacse.org/daily/ppt/2005/
wget -r ftp://prism.nacse.org/daily/ppt/2006/
wget -r ftp://prism.nacse.org/daily/ppt/2007/ 
wget -r ftp://prism.nacse.org/daily/ppt/2008/
wget -r ftp://prism.nacse.org/daily/ppt/2009/
wget -r ftp://prism.nacse.org/daily/ppt/2010/
wget -r ftp://prism.nacse.org/daily/ppt/2011/
wget -r ftp://prism.nacse.org/daily/ppt/2012/ 
wget -r ftp://prism.nacse.org/daily/ppt/2013/ 
wget -r ftp://prism.nacse.org/daily/ppt/2014/ 
wget -r ftp://prism.nacse.org/daily/ppt/2015/ 
wget -r ftp://prism.nacse.org/daily/ppt/2016/ 
wget -r ftp://prism.nacse.org/daily/ppt/2017/ 
wget -r ftp://prism.nacse.org/daily/ppt/2018/ 
wget -r ftp://prism.nacse.org/daily/ppt/2019/ 
wget -r ftp://prism.nacse.org/daily/ppt/2020/ 
wget -r ftp://prism.nacse.org/daily/ppt/2021/ 
 
exec bash